### ISSUE TITLE
capture audio and keep the audio playback in speaker

### ISSUE THREAD

**Issue by bill-hu** [rogerwang/nw-tab-capture#3]
hi, 
 i need to capture a tab content with audio,and keep the audio playback,just with catpure setting like this,

 chrome.tabCapture.capture({ audio: true, video: true }, onTabStream);

and use iframe to show web instead of using webview to capture the audio

is there any setting can do this?

i noticed when the debug window is open  in  SDK version of nw.js,the audio is playbacked as i wanted

thanks

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by bill-hu** [comment]
thanks a lot

From: Roger Wang (WenRui)
Date: 2020-02-22 09:01
To: rogerwang/nw-tab-capture
CC: bill-hu; Author
Subject: Re: [rogerwang/nw-tab-capture] capture audio and keep the audio playback in speaker (#3)
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
